version: '3.9'

services:
  brain-0:
    image: ghcr.io/0-5788719150923125/one:latest
    command: node --max-old-space-size=${MEMORY:-1024} src/pcb.js
    restart: unless-stopped
    user: 1000:1000
    build:
      context: .
      dockerfile: Dockerfile.${ARCH:-x64}
    volumes:
      - gun:/gun
      - ./src:/one/src
      - ./data:/one/data
    environment:
      MEMORY: 4096
      NETWORK_TYPE: resistor
      USE_GUN: 'true'
      NETWORK_WIDTH: 64
      NETWORK_DEPTH: 3
      BATCH_SIZE: 256
      TRAIN_CONTEXT_LENGTH: 9
      LEARNING_RATE: 0.001
      ERROR_THRESH: 0.000001
      REGC: 0.000001
      CLIPVAL: 6.66
      SMOOTHEPS: 1e-8
      SECTION_SIZE: 100000000
      PREDICTION_LENGTH: 333
      DECAY_RATE: 0.999
      MASK_CHANCE: 0.0
      CB_PERIOD: 10

  kv:
    image: redis:7.0.5-alpine
    command: redis-server --save 60 1
    restart: unless-stopped
    volumes:
      - redis:/data

volumes:
  gun:
  redis:
