version: '3.9'

services:
  brain-1:
    image: ghcr.io/0-5788719150923125/one:latest
    command: node --max-old-space-size=${MEMORY:-1024} src/resistor.js
    restart: unless-stopped
    user: 1000:1000
    build:
      context: .
      dockerfile: Dockerfile.${ARCH:-x64}
    deploy:
      resources:
        limits:
          cpus: ${CPUS:-4.0}
    network_mode: 'host'
    volumes:
      - ./src:/one/src
      - ./data:/one/data
    environment:
      FOCUS: ${FOCUS:-trade}
      NETWORK_WIDTH: ${NETWORK_WIDTH:-144}
      NETWORK_DEPTH: ${NETWORK_DEPTH:-6}
      CONTEXT_LENGTH: ${CONTEXT_LENGTH:-5}
      BATCH_SIZE: 6
      TRAINING_SAMPLES: 1024
      LEARNING_RATE: 0.001
      REGC: 0.00001
      CLIPVAL: 23

  brain-2:
    image: ghcr.io/0-5788719150923125/one:latest
    command: node --max-old-space-size=${MEMORY:-1024} src/resistor.js
    restart: unless-stopped
    user: 1000:1000
    build:
      context: .
      dockerfile: Dockerfile.${ARCH:-x64}
    deploy:
      resources:
        limits:
          cpus: ${CPUS:-4.0}
    network_mode: 'host'
    volumes:
      - ./src:/one/src
      - ./data:/one/data
    environment:
      FOCUS: opencog
      NETWORK_WIDTH: 64
      NETWORK_DEPTH: 3
      CONTEXT_LENGTH: ${CONTEXT_LENGTH:-5}
      BATCH_SIZE: 6
      TRAINING_SAMPLES: 1024
      LEARNING_RATE: 0.001
      REGC: 0.00001
      CLIPVAL: 23

  brain-3:
    image: ghcr.io/0-5788719150923125/one:latest
    command: node --max-old-space-size=${MEMORY:-1024} src/resistor.js
    restart: unless-stopped
    user: 1000:1000
    build:
      context: .
      dockerfile: Dockerfile.${ARCH:-x64}
    deploy:
      resources:
        limits:
          cpus: ${CPUS:-4.0}
    network_mode: 'host'
    volumes:
      - ./src:/one/src
      - ./data:/one/data
    environment:
      FOCUS: ${FOCUS:-trade}
      NETWORK_WIDTH: 128
      NETWORK_DEPTH: 4
      CONTEXT_LENGTH: ${CONTEXT_LENGTH:-5}
      BATCH_SIZE: 6
      TRAINING_SAMPLES: 1024
      LEARNING_RATE: 0.001
      REGC: 0.00001
      CLIPVAL: 23

  brain-4:
    image: ghcr.io/0-5788719150923125/one:latest
    command: node --max-old-space-size=${MEMORY:-1024} src/resistor.js
    restart: unless-stopped
    user: 1000:1000
    build:
      context: .
      dockerfile: Dockerfile.${ARCH:-x64}
    deploy:
      resources:
        limits:
          cpus: ${CPUS:-4.0}
    network_mode: 'host'
    volumes:
      - ./src:/one/src
      - ./data:/one/data
    environment:
      FOCUS: rock
      NETWORK_WIDTH: 256
      NETWORK_DEPTH: 18
      CONTEXT_LENGTH: ${CONTEXT_LENGTH:-5}
      BATCH_SIZE: 6
      TRAINING_SAMPLES: 1024
      LEARNING_RATE: 0.001
      REGC: 0.00001
      CLIPVAL: 23

  kv:
    image: redis:7.0.5-alpine
    command: redis-server --save 300 1
    restart: unless-stopped
    ports:
      - 6379:6379
    volumes:
      - redis:/data

volumes:
  redis:
