version: '3.9'

services:
  brain-0:
    image: ghcr.io/0-5788719150923125/one:latest
    command: node --max-old-space-size=${MEMORY:-1024} src/pcb.js
    restart: unless-stopped
    network_mode: host
    user: 1000:1000
    build:
      context: .
      dockerfile: Dockerfile.${ARCH:-x64}
    volumes:
      - ./src:/one/src
      - ./data:/one/data
    environment:
      MEMORY: 8192
      NETWORK_TYPE: transistor
      NETWORK_WIDTH: 64
      NETWORK_DEPTH: 64
      BATCH_SIZE: 1
      LEARNING_RATE: 0.001
      MOMENTUM: 0.1
      REGC: 0.000001
      CLIPVAL: 5.9
      TRAIN_CONTEXT_LENGTH: 23

  kv:
    image: redis:7.0.5-alpine
    command: redis-server --save 60 1
    restart: unless-stopped
    network_mode: host
    volumes:
      - redis:/data

volumes:
  redis:
