version: '3.9'

services:
  brain:
    image: ghcr.io/0-5788719150923125/one:i
    restart: unless-stopped
    user: 1000:1000
    build:
      context: .
      dockerfile: Dockerfile
    deploy:
      resources:
        limits:
          cpus: '4.0'
          memory: 4000M
    volumes:
      - ./src:/one/src
    environment:
      NETWORK_WIDTH: 144
      NETWORK_DEPTH: 6
      BATCH_SIZE: 6
      TRAINING_SAMPLES: 1024
      LEARNING_RATE: 0.001
      REGC: 0.00001
      CLIPVAL: 23

  kv:
    image: redis:7.0.5-alpine
    command: redis-server --save 300 1
    restart: unless-stopped
    volumes:
      - redis:/data

volumes:
  redis:
