version: '3.9'

services:
  brain-0:
    image: ghcr.io/0-5788719150923125/one:latest
    command: node --max-old-space-size=${MEMORY:-1024} src/pcb.js
    restart: unless-stopped
    network_mode: host
    user: 1000:1000
    build:
      context: .
      dockerfile: Dockerfile.${ARCH:-x64}
    volumes:
      - ./src:/one/src
      - ./data:/one/data
    environment:
      FOCUS: ${FOCUS:-trade}
      MEMORY: ${MEMORY:-4096}
      NETWORK_TYPE: resistor
      USE_GUN: ${USE_GUN:-false}
      NETWORK_WIDTH: ${NETWORK_WIDTH:-64}
      NETWORK_DEPTH: ${NETWORK_DEPTH:-4}
      BATCH_SIZE: ${BATCH_SIZE:-32}
      LIST_SIZE: ${LIST_SIZE:-256}
      LEARNING_RATE: ${LEARNING_RATE:-0.001}
      ERROR_THRESH: 0.000001
      REGC: ${REGC:-0.000001}
      CLIPVAL: ${CLIPVAL:-5.9}
      SMOOTHEPS: ${SMOOTHEPS:-1e-8}
      SECTION_SIZE: 100000000
      PREDICTION_LENGTH: 23
      DECAY_RATE: ${DECAY_RATE:-0.999}
      MASK_CHANCE: 0.0
      CB_PERIOD: 1
      SYNAPSE_RESET_THRESHOLD: 100000

  kv:
    image: redis:7.0.5-alpine
    command: redis-server --save 60 1
    restart: unless-stopped
    network_mode: host
    volumes:
      - redis:/data

  # relay:
  #   image: registry.gitlab.com/the-resistance/relay:0.2020.1239
  #   restart: unless-stopped
  #   environment:
  #     PROFILE: true

volumes:
  redis:
