version: '3.9'

services:
  brain:
    image: ghcr.io/0-5788719150923125/one:latest
    restart: unless-stopped
    user: 1000:1000
    build:
      context: .
      dockerfile: Dockerfile.ARM
    environment:
      FOCUS: support
      NETWORK_WIDTH: 256
      NETWORK_DEPTH: 12
      BATCH_SIZE: 6
      TRAINING_SAMPLES: 1024
      LEARNING_RATE: 0.001
      REGC: 0.00001
      CLIPVAL: 23
      CONTEXT_LENGTH: 3

  kv:
    image: redis:7.0.5-alpine
    command: redis-server --save 300 1
    restart: unless-stopped
    volumes:
      - redis:/data

volumes:
  redis:
