version: '3.9'

services:
  brain-0:
    image: ghcr.io/0-5788719150923125/one:latest
    command: node --max-old-space-size=${MEMORY:-1024} src/pcb.js
    restart: unless-stopped
    network_mode: host
    user: 1000:1000
    build:
      context: .
      dockerfile: Dockerfile.${ARCH:-x64}
    volumes:
      - ./src:/one/src
      - ./data:/one/data
    environment:
      FOCUS: ${FOCUS:-trade}
      MEMORY: ${MEMORY:-4096}
      NETWORK_TYPE: circuit
      USE_GUN: ${USE_GUN:-false}
      NETWORK_WIDTH: 64
      NETWORK_DEPTH: 6
      BATCH_SIZE: 64
      LIST_SIZE: 64
      LEARNING_RATE: 0.001
      ERROR_THRESH: 0.000001
      REGC: 0.000001
      CLIPVAL: 5000000000
      SMOOTHEPS: 1e-8
      SECTION_SIZE: 100000000
      PREDICTION_LENGTH: 23
      DECAY_RATE: 0.999
      MASK_CHANCE: 0.0
      CB_PERIOD: 1

  kv:
    image: redis:7.0.5-alpine
    command: redis-server --save 60 1 --loglevel warning
    restart: unless-stopped
    network_mode: host
    volumes:
      - redis:/data

  # relay:
  #   image: registry.gitlab.com/the-resistance/relay:0.2020.1239
  #   restart: unless-stopped
  #   environment:
  #     PROFILE: true

volumes:
  redis:
